"""Update seed

Revision ID: 54e7f481f86f
Revises: d6cd0dc160f9
Create Date: 2023-08-08 09:12:37.622625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e7f481f86f'
down_revision = 'd6cd0dc160f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
