"""Updates seed again

Revision ID: 9fc9485c7338
Revises: 54e7f481f86f
Create Date: 2023-08-08 10:52:03.506780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc9485c7338'
down_revision = '54e7f481f86f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
